#!/bin/bash

export j="/projects/sate7/tools/bin/astral.3.0.0.jar"

out=$2

if [ -s $out ]; then
  echo "Ouput files exists. Refusing to rerun. "
  exit 0;
fi

java -jar $j -i $1 -wq -o $out 1>$out.astral.out 2>$out.astral.err

test "$?" != "0" && exit 1


echo ASTRAL Done. Output at: $out
