#!/bin/bash

dir=scaledup2.10reps.supergenes-$1bp-$2/R$3

echo '+Group = "GRAD"
+Project = "COMPUTATIONAL_BIOLOGY"
+ProjectDescription = "Binning"

Universe = vanilla

Requirements = Arch == "X86_64" 

executable = '`pwd`'/runraxml-introns-2-fixed.sh

Log = logs/supergene-'$1'-'$2'-R'$3'-condor.boot.log

getEnv=True 
'>condor.boot.$1.$2.R$3

for x in `ls $dir`; do
  if [ -f `pwd`/$dir/$x/.done.raxml.gtrgamma.200.2 ]; then
    echo $x is done
  else
    echo "
 Arguments = $x 1 `pwd`/$dir supergene.fasta
 Error=logs/boot-$x-$1-$2-$3-std.err
 Output=logs/boot-$x-$1-$2-$3-std.out
 Queue">>condor.boot.$1.$2.R$3
 fi
done
