#!/bin/bash

echo "USAGE: $0 [dir name] [rep number]"

dir=$1/R$2
REP=200

echo '+Group = "GRAD"
+Project = "COMPUTATIONAL_BIOLOGY"
+ProjectDescription = "Binning"

Universe = vanilla

Requirements = Arch == "X86_64" 

executable = '$WS_HOME'/global/src/shell/runraxml.bs.sh

Log = logs/supergene-'$1'-R'$2'-condor.boot.log

getEnv=True 
'>condor.boot.$1.R$2

for x in `ls $dir`; do
  if [ -f `pwd`/$dir/$x/.done.raxml.gtrgamma.200.2 ]; then
    echo $x is done
  else
    echo "
 Arguments = $x 1 `pwd`/$dir supergene.fasta $REP
 Error=logs/boot-$x-$1-$2-std.err
 Output=logs/boot-$x-$1-$2-std.out
 Queue">>condor.boot.$1.R$2
 fi
done

echo condor_submit condor.boot.$1.R$2
