#!/bin/bash
#set -x
tmp=`mktemp "control_XXXXX"`

fn=`basename $1`
ln -s $1 ./$fn

echo "$fn
0
$RANDOM
`cat $1|wc -l` `cat $2|wc -l` 
`cat $2`
0
"> $tmp

/projects/sate7/tools/bin/mpest.1.2.64bit $tmp

test $? == 1 || exit 1

mv $fn.tre $fn.tre.mpest
grep "tree mpest" $fn.tre.mpest |sed -e "s/.* //g" > $fn.tre

tar cvfj logs.$fn.tar.bz --remove-files $tmp $fn.tre.mpest 
