#!/bin/bash

echo "USAGE: $0 dir_name [rep number]"
test $# -gt 0 || exit 1

dir=$1
test $# == 1 || dir=$1/R$2
name=$1
test $# == 1 || name=$1-R$2

REP=200

echo '+Group = "GRAD"
+Project = "COMPUTATIONAL_BIOLOGY"
+ProjectDescription = "Gene Tree"

Universe = vanilla

Requirements = Arch == "X86_64" 

executable = '$WS_HOME'/global/src/shell/runraxml.bs.sh

Log = logs/supergene-'$name'-condor.boot.log

getEnv=True 
'>condor.boot.$name

for x in `ls $dir`; do
  if [ -f `pwd`/$dir/$x/.done.raxml.gtrgamma.200.2 ]; then
    echo $x is done
  else
    echo "
 Arguments = $x 1 `pwd`/$dir supergene.fasta $REP
 Error=logs/boot-$x-$name-std.err
 Output=logs/boot-$x-$name-std.out
 Queue">>condor.boot.$name
 fi
done

echo condor_submit condor.boot.$name
